//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRIntant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Преподаватель
    {
        public int id { get; set; }
        public string фамилия { get; set; }
        public string имя { get; set; }
        public string отчество { get; set; }
        public string кабинет { get; set; }
        public string класс { get; set; }
        public string предмет { get; set; }
        public Nullable<System.DateTime> дата_и_время_урока { get; set; }
    }
}
